### ISSUE TITLE
lib32-mesa loading error in 32bits wine apps

### ISSUE THREAD

**Issue by guillaume70** [manjaro/packages-multilib#6]
radeonsi_dri.so (lib32-mesa) doesn't load when i run some 32bits wine applications. so these applications don't run.

i have a 64bits Manjaro installation, openbox edition. integrated graphic processor (Radeon HD 8400 / R3 Series). i use the free driver (xf86-video-ati).

```shell:
┌─[sam. janv. 02][guigui@guigui-ordi:~]
└─> uname -a
Linux guigui-ordi 4.1.15-1-MANJARO #1 SMP PREEMPT Tue Dec 15 07:48:44 UTC 2015 x86_64 GNU/Linux
┌─[sam. janv. 02][guigui@guigui-ordi:~]
└─>
```

i installed 32bits Windows games (Baldur's Gate and Diablo II) with wine (playonlinux). it worked for weeks.
but since december 30 (more or less), Baldur's Gate and Diablo II don't run:

```shell:
┌─[jeu. déc. 31][guigui@guigui-ordi:~]
└─> /usr/share/playonlinux/playonlinux --run "BGMain" %F
Looking for python... 3.5.1 - skipped
Looking for python2.7... 2.7.11 - wxversion(s): 3.0-gtk2
selected
/usr/share/themes/Loma/gtk-2.0/gtkrc:47: Murrine configuration option "hilight_ratio" will be deprecated in future releases. Please use "highlight_shade" instead.
/usr/share/themes/Loma/gtk-2.0/gtkrc:49: Murrine configuration option "scrollbar_color" is no longer supported and will be ignored.
/usr/share/themes/Loma/gtk-2.0/gtkrc:50: Murrine configuration option "gradients" is no longer supported and will be ignored.
16:54:01: Debug: Failed to connect to session manager: SESSION_MANAGER environment variable not defined
[main] Message: PlayOnLinux (4.2.9) is starting
[clean_tmp] Message: Cleaning temp directory
Script started /home/guigui/.PlayOnLinux/shortcuts/BGMain
[POL_System_CheckFS] Message: Checking filesystem for BGMain.exe
[POL_Wine] Message: Running wine-1.6.2 BGMain.exe %F (Working directory : /home/guigui/.PlayOnLinux/wineprefix/Baldur/drive_c/GOG Games/Baldur's Gate)
[POL_Wine] Message: Notice: PlayOnLinux deliberately disables winemenubuilder. See http://www.playonlinux.com/fr/page-26-Winemenubuilder.html
[POL_Wine] Message: Wine return: 0
libGL error: unable to load driver: radeonsi_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: radeonsi
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  155 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  324
  Current serial number in output stream:  328
┌─[jeu. déc. 31][guigui@guigui-ordi:~]
└─>
```

the 27 of december it worked.

i don't do anything special between december 27 and 30 (except the little Manjaro updates).

i downgraded lib32-mesa (11.1.0-1) to the prior version (11.0.8-0.1), and it works!

so i think it's a bug in lib32-mesa 11.1.0-1

**Comment by philmmanjaro** [comment]
Ok, thx for the information. We will look into it. You can use the application **downgrade** to even mark that package to be blacklisted so no updates will happen until it is fixed.

**Comment by guillaume70** [comment]
same problem with lib32-mesa 11.2.1-1 ...

**Comment by guillaume70** [comment]
now it's worse: i updated my system today (2016-05-15) and, even with lib32-mesa 11.0.8-0.1, i have the same problem!

of course, it's also the same problem with the new lib32-mesa (11.2.2-1).

so now i can't use the free driver for some 32bits wine applications anymore!

!!!...

any solutions?... (with the free driver)

PS: ( uname -a -> Linux guigui-ordi 4.4.10-1-MANJARO #1 SMP PREEMPT Wed May 11 22:01:52 UTC 2016 x86_64 GNU/Linux )

**Comment by guillaume70** [comment]
i found a solution:

delete/rename libgpg-error.so* in the corresponding wine directory of the user.

for me it is:
~/.PlayOnLinux/wine/linux-x86/1.6.2/lib

(where "1.6.2" is the wine version i use for the game in question)

i this directory i had libgpg-error.so.0.4.0, libgpg-error.so.0, and libgpg-error.so
so i delete/rename them.

now it works!
